CREATE TABLE `unused_letter` (
`id` INT NOT NULL AUTO_INCREMENT,
`letter` VARCHAR(1) DEFAULT NULL,
`game_id` INT DEFAULT NULL,

PRIMARY KEY(`id`),
KEY `FK_GAME_idx_3` (`game_id`),

CONSTRAINT `FK_GAME_3`
FOREIGN KEY (`game_id`)
REFERENCES `game` (`id`)

ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;