CREATE TABLE IF NOT EXISTS `game` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`attempts_left` INT,
`word` VARCHAR(20) DEFAULT NULL,
`word_reveal` VARCHAR(20) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
