CREATE TABLE `game` (
`id` VARCHAR(45) PRIMARY KEY,
`attempts_left` INT,
`word` VARCHAR(20) DEFAULT NULL,
`word_reveal` VARCHAR(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `original_letter` (
`id` INT NOT NULL AUTO_INCREMENT,
`letter` VARCHAR(1) DEFAULT NULL,
`game_id` VARCHAR(45),

PRIMARY KEY(`id`),
KEY `FK_GAME_idx` (`game_id`),

CONSTRAINT `FK_GAME`
FOREIGN KEY (`game_id`)
REFERENCES `game` (`id`)

ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `hidden_letter` (
`id` INT NOT NULL AUTO_INCREMENT,
`letter` VARCHAR(1) DEFAULT NULL,
`game_id` VARCHAR(45),

PRIMARY KEY(`id`),
KEY `FK_GAME_idx` (`game_id`),

FOREIGN KEY (`game_id`)
REFERENCES `game` (`id`)

ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `unused_letter` (
`id` INT NOT NULL AUTO_INCREMENT,
`letter` VARCHAR(1) DEFAULT NULL,
`game_id` VARCHAR(45),

PRIMARY KEY(`id`),
KEY `FK_GAME_idx` (`game_id`),

FOREIGN KEY (`game_id`)
REFERENCES `game` (`id`)

ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;